### ISSUE TITLE
Specification Template

### ISSUE THREAD

**Issue by TsyTi** [ipsaone/Software-Architecture#3]
From ECSS ? NASA ? Custom ??
ECSS reference : https://ecss.nl/standard/ecss-e-st-10-06c-technical-requirements-specification/

**Comment by pwnorbitals** [comment]
[Specifications example.xlsx](https://github.com/ipsaone/Software-Architecture/files/5568804/Specifications.example.xlsx)

**Comment by TsyTi** [comment]
We have a template
